# Generated by Django 5.1.3 on 2024-11-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_y_nombres', models.CharField(max_length=100)),
                ('puesto_institucional', models.CharField(max_length=100)),
                ('unidad_perteneciente', models.CharField(max_length=100)),
                ('direccion_institucional', models.CharField(max_length=200)),
                ('ciudad_laboral', models.CharField(max_length=100)),
                ('telefono_institucional', models.CharField(max_length=15)),
                ('extension_telefonica', models.CharField(default='00000', max_length=5)),
                ('correo_institucional', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Programador',
                'verbose_name_plural': 'Programadores',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chofer')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reservante', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala')),
            ],
            options={
                'unique_together': {('fecha', 'sala', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
