# Generated by Django 5.1.3 on 2024-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
