# Generated by Django 5.1.3 on 2024-11-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chofer_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_llegada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
