# Generated by Django 5.1.3 on 2024-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_viaje_fecha_llegada_alter_viaje_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
