# Generated by Django 5.1.3 on 2024-11-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_viaje_fecha_llegada'),
    ]

    operations = [
    ]
