# Generated by Django 5.1.3 on 2024-11-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20241112_1219'),
    ]

    operations = [
    ]
