# Generated by Django 5.1.3 on 2024-11-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20241112_1233'),
    ]

    operations = [
    ]
