# Generated by Django 5.1.3 on 2024-11-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20241112_1259"),
    ]

    operations = []
