# Generated by Django 5.1.3 on 2024-12-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_viaje_viaticos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viaje",
            name="viaticos",
            field=models.CharField(
                choices=[
                    ("con_viaticos", "Con Viáticos"),
                    ("sin_viaticos", "Sin Viáticos"),
                ],
                default="sin_viaticos",
                max_length=20,
            ),
        ),
    ]
